### ISSUE TITLE
Get-ADSIGroupMembership

### ISSUE THREAD

**Issue by jmloubser** [lazywinadmin/AdsiPS#4]
Hello, 

This function does not work for AD Groups with lots of members?
I was successful with an AD Group that contains 502 members
Unable to get list with AD Group with 5000+
Are there a limitation?

Thanks

**Comment by lazywinadmin** [comment]
Thanks for the feedback, will check it out.

**Comment by lazywinadmin** [comment]
I updated the module with a new version of Get-ADSIGroupMembership.
There is a dependancy on New-ADSIPrincipalContext, which i also added in the new version.

Let me know

**Comment by jmloubser** [comment]
Hello,
When I try to use it, I receive error?  I include my steps and error for your information:

Downloaded the new AdsiPS-master.zip file and extracted to D:\Temp\AdsiPS
Run PowerShell as Administrator
> d:
> cd \temp\AdsiPS
> Set-ExecutionPolicy unrestricted
> Import-module .\AdsiPs.psm1
> $Cred = Get-Credential
> $TestContext = New-ADSIPrincipalContext -PrincipalContextType Domain -Credential $Cred

ERROR:
New-ADSIPrincipalContext : Unable to find type [System.DirectoryServices.AccountManagement.PrincipalContext]: make sure that the assembly 
containing this type is loaded.
At line:1 char:16
+ $TestContext = New-ADSIPrincipalContext -PrincipalContextType Domain -Credential ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Director...rincipalContext:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound


Please let me know what I am dong wrong testing the new code...

Thanks

**Comment by lazywinadmin** [comment]
Woops Sorry I'm currently editing the code. Can you give another shot with the last version i uploaded?

**Comment by jmloubser** [comment]
You have a winner!

I tested Get-ADSIGroupMembership with two AD Groups with memberships of 5,432 and 15,788 

Thanks, I appreciate your prompt response and excellent work.
