### ISSUE TITLE
ValueFromPipelineByPropertyName in Disable-ADSIComputer

### ISSUE THREAD

**Issue by evetsleep** [lazywinadmin/AdsiPS#5]
From what I understand (this is the first I've seen someone do this):

```powershell
[parameter(Mandatory = $true, ValueFromPipelineByPropertyName = "SamAccountName", ValueFromPipeline = $true)]
```
ValueFromPipelineByPropertyName takes a bool as its value.  I took a look at [MSDN](https://msdn.microsoft.com/en-us/library/system.management.automation.parameterattribute.valuefrompipelinebypropertyname(v=vs.85).aspx) and it would appear that proper values are indeed $true or $false.

Or am I wrong and missing someting?

**Comment by lazywinadmin** [comment]
Thanks @evetsleep ! Definitely a typo that I carried over multiple functions... -_-

Fixed in the last   ##Commit.

Thanks again!
