### ISSUE TITLE
ADSIForest ask for another param

### ISSUE THREAD

**Issue by christophekumor** [lazywinadmin/AdsiPS#60]
**Reproduce :**
`Get-ADSIForest -ForestName lazywinadmin.com`

it will ask to input ContextType Parameter.

**Reason :**
when specify -ForestName  or -Credential , the function call New-ADSIDirectoryContext.
New-ADSIDirectoryContext have ContextType as mandatory parameter.

**Comment by lazywinadmin** [comment]
Fixed by PR #66
