### ISSUE TITLE
Get-ADSIPrincipalGroupMembership does not accept ComputerName as Identity

### ISSUE THREAD

**Issue by PZan** [lazywinadmin/AdsiPS#98]
Computers can be part of AD groups as well. By modifying line 3510 - 3519 of AdsiPS.psm1 I got it working for computers as well:
`                if (($FoundObjectObjectClass -contains "computer") -or ($FoundObjectObjectClass -contains "computer")) {
                    $UserInfos = Get-ADSIComputer -Identity $FoundObject.samaccountName
                    $UnderlyingProperties = $UserInfos.GetUnderlyingObject()
                    $ObjectGroups += Get-ADSIUserPrimaryGroup -Identity $UserInfos -ReturnNameAndDescriptionOnly
                }
                elseif (($FoundObjectObjectClass -contains "person") -or ($FoundObjectObjectClass -contains "user")) {
                    $UserInfos = Get-ADSIUser -Identity $FoundObject.samaccountName
                    $UnderlyingProperties = $UserInfos.GetUnderlyingObject()
                    $ObjectGroups += Get-ADSIUserPrimaryGroup -Identity $UserInfos -ReturnNameAndDescriptionOnly
                }
                elseif ($FoundObjectObjectClass -contains "group") {
                    $GroupInfos = Get-ADSIGroup -Identity $FoundObject.samaccountName
                    $UnderlyingProperties = $GroupInfos.GetUnderlyingObject()
                }`
Sorry for not formatting better, but I'm thinking this is quite a simple fix, so hoping you'll accept it the way it is :)

**Comment by oze4** [comment]
@PZan I put in a pull request for this issue. FYI.

**Comment by lazywinadmin** [comment]
Thanks @PZan for reporting this and @oze4 for the quick change! Appreciated
